version: '3.8'

services:
  spark-master:
    container_name: da-spark-master
    build: .
    image: spark-image:spark-image-3.5.0
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'
  
  spark-history-server:
    container_name: da-spark-history
    image: spark-image:spark-image-3.5.0
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'

  spark-worker:
    container_name: da-spark-worker
    image: spark-image:spark-image-3.5.0
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
  
  spark-jupyter:
    container_name: da-spark-jupyter
    image: pyspark-jupyterlab:spark-3.5.0-jupyterLab
    ports:
      - '8888:8888'
    volumes:
      - ./notebooks:/opt/notebooks
      - spark-logs:/opt/spark/spark-events

volumes:
  spark-logs: