# File: .github/workflows/cd-pipeline.yml

name: Generate Changelog Action

on:
  push:
    branches:
      - main  # or your deployment branch
    paths:
      - 'basic-nodejs-express-server/**'  # only run when this directory is changed

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate changelog
        uses: scottbrenner/generate-changelog-action@master
        env:
          REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add CHANGELOG.md
          git commit -m "chore: update changelog [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
